# Generated by Django 2.2.16 on 2022-11-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221111_1137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscription',
            table='subscriptions',
        ),
    ]
