# Generated by Django 2.2.16 on 2022-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221111_1138'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('ingredient', 'amount'), name='unique_ingredient_recipe'),
        ),
        migrations.AlterModelTable(
            name='ingredientrecipe',
            table='ingredientrecipes',
        ),
    ]
