# Generated by Django 2.2.16 on 2022-10-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221020_1428'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favorite',
            table='favorite',
        ),
    ]
