# Generated by Django 2.2.16 on 2022-10-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221021_0050'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favorite',
            table='favorites',
        ),
    ]
